#pragma once

// =============================================================================
//  WEEK 2 - the IDE's shell: the panel list, the menu bar, and the dockspace.
//
//  *** ADDING A PANEL IS ONE LINE. *** AddPanel(std::make_unique<Whatever>());
//  It was done nine more times after Week 2, and every one of those was one
//  line, because the View menu is GENERATED by looping the panel list rather
//  than written out.
//
//  ---------------------------------------------------------------------------
//  THE SELECTION lives here rather than in the Hierarchy panel, because two
//  panels share it - Hierarchy selects, Inspector displays - and a panel
//  reaching into another panel is worse than both reaching into the shell.
//
//  IT IS AN EntityHandle, NEVER AN Entity*. A cached pointer crashes the first
//  time Week 10 destroys the selected entity mid-frame; a handle is checked
//  and reported. That is the argument Handle.h makes, arriving from the tools
//  side - and it is why real engines adopt handles the moment they grow an
//  editor.
// =============================================================================

#include <engine/Engine.h>

#include <memory>
#include <string>
#include <vector>

#include "panels/Panel.h"

namespace editor {

// Shared editor state. Passed nowhere - panels reach it through Get() - which
// is a deliberate simplification: this is a debug tool with exactly one
// instance, and threading a context pointer through ten panels would be
// ceremony with no payoff.
struct EditorState {
    eng::EntityHandle selected{};
    bool              showImGuiDemo = false;

    // Set by any panel that mutates the scene, cleared on save. Purely a
    // prompt to the user - the editor does not block anything on it, because a
    // debug tool that refuses to close is worse than one that loses an edit.
    bool              dirty = false;

    // Raised by the Toolbar when Play is pressed; consumed by EditorApp, which
    // is the only thing that holds the Game panel. A flag rather than a direct
    // call so no panel needs a pointer to another panel.
    bool              focusGameView = false;

    // A scene the Asset Browser asked to open, applied by EditorApp AFTER every
    // panel has drawn.
    //
    // DEFERRED, and it has to be. Loading destroys every entity in the scene;
    // doing that from inside a panel's Draw would pull the ground out from
    // under the panels that have already drawn this frame and are holding
    // pointers into the entity they were describing. It is the same argument
    // DeferredOps makes for the engine, arriving at the editor - and the
    // editor does not get to be exempt from the engine's own rules.
    std::string       requestedScene;

    static EditorState& Get();
};

class EditorApp {
public:
    bool Init();
    void Run();
    void Shutdown();

    // One line to add a panel. Really one line.
    void AddPanel(std::unique_ptr<Panel> panel);

private:
    void DrawMenuBar();
    void DrawPanels();

    // Scene navigation. The list is DISCOVERED from assets/scenes/ rather than
    // hardcoded, so dropping a .json in there puts it in the menu with no
    // rebuild - the same property the scene format has, and an odd one for the
    // editor to be the thing that breaks.
    void RefreshSceneList();
    void LoadScene(const std::string& virtualPath);
    void SaveScene(const std::string& virtualPath);   // empty = save in place
    void DrawSaveAsPopup();

    // Play hands the keyboard to the Game view. Lives here rather than in the
    // panel because the panel is a background tab at the moment it is asked.
    void FocusGameViewIfRequested();

    std::vector<std::unique_ptr<Panel>> m_panels;
    std::vector<std::string>            m_sceneList;

    // The two VIEWS. Owned by m_panels like everything else - these are
    // non-owning back-pointers, because EditorApp has to drive them beyond
    // Draw(): both need RenderView() called after every panel has drawn, and
    // the Game view needs focus routed to it when Play is pressed. Every other
    // panel is reached only through the base class, which is exactly why only
    // these two are named here.
    class ScenePanel* m_scenePanel = nullptr;
    class GamePanel*  m_gamePanel  = nullptr;

    char m_saveAsPath[256]   = {};
    bool m_openSaveAsPopup   = false;
    char m_status[256]       = {};
};

} // namespace editor
