// =============================================================================
//  WEEK 7 - PROVIDED TEST SUITE. DO NOT EDIT THIS FILE.
//
//  Passing this suite is the Milestone 2 verification for the allocators.
//
//  Read it before you write either allocator. It is the specification, and it
//  is more precise than the prose in the headers. In particular it pins down
//  three things students routinely guess wrong:
//
//    - Exhaustion returns nullptr. It does not assert, throw, or grow.
//    - Alignment is honoured for every power-of-two alignment up to 64.
//    - A pool's freed blocks are genuinely reusable, in any order.
//
//  If a case here disagrees with something you assumed, the suite wins.
// =============================================================================

#include <doctest/doctest.h>

#include <engine/memory/PoolAllocator.h>
#include <engine/memory/StackAllocator.h>

#include <cstdint>
#include <set>
#include <vector>

using namespace eng;

namespace {

bool IsAlignedTo(const void* pointer, usize alignment) {
    return (reinterpret_cast<std::uintptr_t>(pointer) % alignment) == 0;
}

} // namespace

// =============================================================================
//  Stack allocator
// =============================================================================

TEST_CASE("stack: a fresh allocator is empty and has the requested capacity") {
    StackAllocator stack(1024);
    CHECK(stack.BytesUsed() == 0);
    CHECK(stack.BytesCapacity() == 1024);
    CHECK(stack.AllocationCount() == 0);
}

TEST_CASE("stack: allocations are distinct, usable, and non-overlapping") {
    StackAllocator stack(1024);

    auto* a = static_cast<u8*>(stack.Allocate(64, 1));
    auto* b = static_cast<u8*>(stack.Allocate(64, 1));

    REQUIRE(a != nullptr);
    REQUIRE(b != nullptr);
    CHECK(a != b);

    // Write the full extent of both. If they overlap, this corrupts one of
    // them and the checks below fail. Run under a sanitizer too - an overrun
    // past the end of the slab is invisible to this test.
    for (usize i = 0; i < 64; ++i) { a[i] = 0xAA; }
    for (usize i = 0; i < 64; ++i) { b[i] = 0xBB; }
    for (usize i = 0; i < 64; ++i) { CHECK(a[i] == 0xAA); }
    for (usize i = 0; i < 64; ++i) { CHECK(b[i] == 0xBB); }
}

TEST_CASE("stack: alignment is honoured for every power of two up to 64") {
    StackAllocator stack(4096);

    for (usize alignment = 1; alignment <= 64; alignment *= 2) {
        // The single-byte allocation before each request deliberately pushes
        // the cursor to an awkward offset, so an implementation that only
        // happens to be aligned does not pass by luck.
        stack.Allocate(1, 1);
        void* p = stack.Allocate(16, alignment);
        REQUIRE(p != nullptr);
        CHECK(IsAlignedTo(p, alignment));
    }
}

TEST_CASE("stack: exhaustion returns nullptr and leaves the allocator usable") {
    StackAllocator stack(128);

    void* big = stack.Allocate(256, 1);
    CHECK(big == nullptr);              // must not assert, throw, or grow

    void* small = stack.Allocate(64, 1);
    CHECK(small != nullptr);            // still works after a refusal
}

TEST_CASE("stack: a zero-size allocation does not corrupt the cursor") {
    StackAllocator stack(256);
    const auto before = stack.GetMarker();
    stack.Allocate(0, 1);
    void* p = stack.Allocate(16, 1);
    CHECK(p != nullptr);
    CHECK(stack.GetMarker() >= before);
}

TEST_CASE("stack: rewinding to a marker reclaims exactly what came after it") {
    StackAllocator stack(1024);

    stack.Allocate(100, 1);
    const auto marker = stack.GetMarker();
    const auto usedAtMarker = stack.BytesUsed();

    stack.Allocate(200, 1);
    stack.Allocate(300, 1);
    CHECK(stack.BytesUsed() > usedAtMarker);

    stack.FreeToMarker(marker);
    CHECK(stack.BytesUsed() == usedAtMarker);
}

TEST_CASE("stack: memory after a rewind is genuinely reusable") {
    StackAllocator stack(1024);

    const auto marker = stack.GetMarker();
    void* first = stack.Allocate(128, 16);
    REQUIRE(first != nullptr);

    stack.FreeToMarker(marker);

    void* second = stack.Allocate(128, 16);
    REQUIRE(second != nullptr);
    CHECK(first == second);             // same bytes handed out again
}

TEST_CASE("stack: nested markers unwind correctly") {
    StackAllocator stack(2048);

    const auto outer = stack.GetMarker();
    stack.Allocate(64, 1);

    const auto inner = stack.GetMarker();
    stack.Allocate(64, 1);
    stack.Allocate(64, 1);

    stack.FreeToMarker(inner);
    const auto afterInner = stack.BytesUsed();

    stack.FreeToMarker(outer);
    CHECK(stack.BytesUsed() < afterInner);
    CHECK(stack.BytesUsed() == 0);
}

TEST_CASE("stack: Clear empties the allocator completely") {
    StackAllocator stack(512);
    stack.Allocate(128, 1);
    stack.Allocate(128, 1);
    stack.Clear();
    CHECK(stack.BytesUsed() == 0);
    CHECK(stack.Allocate(512, 1) != nullptr);
}

TEST_CASE("stack: peak survives a rewind") {
    // Peak is the number that answers "how big does this buffer need to be".
    // It must remember the high-water mark, not the current level.
    StackAllocator stack(1024);

    const auto marker = stack.GetMarker();
    stack.Allocate(512, 1);
    const auto peakAfterAlloc = stack.PeakBytes();
    CHECK(peakAfterAlloc >= 512);

    stack.FreeToMarker(marker);
    CHECK(stack.BytesUsed() == 0);
    CHECK(stack.PeakBytes() == peakAfterAlloc);
}

// =============================================================================
//  Pool allocator
// =============================================================================

TEST_CASE("pool: reports its own geometry") {
    PoolAllocator pool(32, 10);
    CHECK(pool.BlockCount() == 10);
    CHECK(pool.BlocksInUse() == 0);
    CHECK(pool.BlockSize() >= 32);      // may be rounded up for alignment
}

TEST_CASE("pool: every block is distinct and the pool then reports exhaustion") {
    constexpr usize kBlocks = 8;
    PoolAllocator pool(64, kBlocks);

    std::set<void*> handed;
    for (usize i = 0; i < kBlocks; ++i) {
        void* p = pool.Allocate();
        REQUIRE(p != nullptr);
        CHECK(handed.insert(p).second);     // never the same block twice
    }

    CHECK(pool.BlocksInUse() == kBlocks);
    CHECK(pool.Allocate() == nullptr);      // exhausted, no assert, no growth
}

TEST_CASE("pool: every block is aligned") {
    for (usize alignment : {usize{4}, usize{8}, usize{16}, usize{32}, usize{64}}) {
        PoolAllocator pool(48, 16, alignment);
        for (usize i = 0; i < 16; ++i) {
            void* p = pool.Allocate();
            REQUIRE(p != nullptr);
            CHECK(IsAlignedTo(p, alignment));
        }
    }
}

TEST_CASE("pool: blocks do not overlap") {
    constexpr usize kBlocks    = 16;
    constexpr usize kBlockSize = 32;
    PoolAllocator pool(kBlockSize, kBlocks);

    std::vector<u8*> blocks;
    for (usize i = 0; i < kBlocks; ++i) {
        auto* p = static_cast<u8*>(pool.Allocate());
        REQUIRE(p != nullptr);
        blocks.push_back(p);
    }

    // Stamp each block with its own index across its full requested size.
    for (usize i = 0; i < blocks.size(); ++i) {
        for (usize b = 0; b < kBlockSize; ++b) {
            blocks[i][b] = static_cast<u8>(i);
        }
    }
    // If any two blocks overlapped, a later stamp overwrote an earlier one.
    for (usize i = 0; i < blocks.size(); ++i) {
        for (usize b = 0; b < kBlockSize; ++b) {
            CHECK(blocks[i][b] == static_cast<u8>(i));
        }
    }
}

TEST_CASE("pool: a freed block becomes available again") {
    PoolAllocator pool(32, 4);

    void* a = pool.Allocate();
    void* b = pool.Allocate();
    void* c = pool.Allocate();
    void* d = pool.Allocate();
    REQUIRE(pool.Allocate() == nullptr);

    pool.Free(b);
    CHECK(pool.BlocksInUse() == 3);

    void* reused = pool.Allocate();
    REQUIRE(reused != nullptr);
    CHECK(pool.BlocksInUse() == 4);

    (void)a; (void)c; (void)d;
}

TEST_CASE("pool: blocks freed out of order are all reusable") {
    // This is the property that distinguishes a pool from a stack. If your
    // free list is wrong, this is the case that catches it.
    constexpr usize kBlocks = 8;
    PoolAllocator pool(32, kBlocks);

    std::vector<void*> blocks;
    for (usize i = 0; i < kBlocks; ++i) {
        blocks.push_back(pool.Allocate());
    }

    pool.Free(blocks[3]);
    pool.Free(blocks[0]);
    pool.Free(blocks[6]);
    pool.Free(blocks[1]);
    CHECK(pool.BlocksInUse() == kBlocks - 4);

    std::set<void*> reacquired;
    for (usize i = 0; i < 4; ++i) {
        void* p = pool.Allocate();
        REQUIRE(p != nullptr);
        CHECK(reacquired.insert(p).second);
    }
    CHECK(pool.Allocate() == nullptr);
    CHECK(pool.BlocksInUse() == kBlocks);
}

TEST_CASE("pool: a full allocate/free cycle returns to the starting state") {
    constexpr usize kBlocks = 32;
    PoolAllocator pool(16, kBlocks);

    for (int cycle = 0; cycle < 100; ++cycle) {
        std::vector<void*> blocks;
        for (usize i = 0; i < kBlocks; ++i) {
            void* p = pool.Allocate();
            REQUIRE(p != nullptr);
            blocks.push_back(p);
        }
        for (void* p : blocks) {
            pool.Free(p);
        }
        REQUIRE(pool.BlocksInUse() == 0);
    }
    // A hundred cycles with no drift. A free list that loses a block each
    // round would fail somewhere in here rather than on the first pass.
    CHECK(pool.BlocksInUse() == 0);
}

TEST_CASE("pool: peak survives blocks being returned") {
    PoolAllocator pool(16, 8);

    std::vector<void*> blocks;
    for (usize i = 0; i < 8; ++i) { blocks.push_back(pool.Allocate()); }
    CHECK(pool.PeakBlocksInUse() == 8);

    for (void* p : blocks) { pool.Free(p); }
    CHECK(pool.BlocksInUse() == 0);
    CHECK(pool.PeakBlocksInUse() == 8);
}

TEST_CASE("pool: freeing null is harmless") {
    PoolAllocator pool(16, 4);
    pool.Free(nullptr);
    CHECK(pool.BlocksInUse() == 0);
}
